name: Pull request naming convention rules

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events for the listed branches
  push:
    branches:
      - Integration
  pull_request:
    branches:
      - Integration

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  job_1:
    name: Pull Request naming convention
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    
    steps:
     - uses: deepakputhraya/action-pr-title@v1.0.2
       with:
        regex: '^TN' # Regex the title should match.
        min_length: 4 # Min length of the title
        max_length: 20 # Max length of the title
        github_token: ${{ github.token }} # Default: ${{ github.token }}
