name: PR Description Checker

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events for the listed branches
  push:
    branches:
      - Integration
  pull_request:
    branches:
      - Integration

jobs:
  job_1:
    name: PR description is completed
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Use Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: PR description is completed
        run: |
          # Get the PR description
          PR_DESCRIPTION=$(jq -r '.pull_request.body' $GITHUB_EVENT_PATH)
          
          # Define the expected pattern for PR descriptions
          EXPECTED_PATTERN='(?i).*Is this a BAU or project-based change?.*'
          
          # Check if PR description matches the expected pattern
          if [[ ! $PR_DESCRIPTION =~ $EXPECTED_PATTERN ]]; then
            echo "Invalid PR description. Please complete the default template."
            exit 1
          fi
